[package]
name = "struct-input-derive"
version = "0.1.0"
edition = "2024"
authors = ["Yunseong Jeong <me@yunseong.dev>"]
description = "Procedural derive macro for the struct-input crate, enabling automatic mapping of CLI inputs to struct fields."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
darling = "0.23.0"
proc-macro2 = "1.0.106"