[package]
name = "struct-input"
version = "0.1.0"
edition = "2024"
authors = ["Yunseong Jeong <me@yunseong.dev>"]
description = "A Rust crate for mapping interactive CLI user input directly to structs with declarative validation and async support."
license = "MIT"

[dependencies]
struct-input-derive = { version = "0.1.0", path = "./struct-input-derive" }

regex = "1.12.3"
tokio = { version = "1.49.0", features = ["full"] }
